---
# the name of our website
site_name: India Investments Wiki

# the URL of our site
site_url: https://staging.indiainvestments.wiki

# enable "edit this page" feature and link to our github repo
repo_url: https://github.com/indiainvestments/mkdocswiki

# the label of the GitHub button
repo_name: "India Investments Wiki"

# we can hide the edit button if we want
# edit_uri:

# other useful parameters to add info in meta tags
# site_description:
# site_author:
# copyright:

# in case we need GA
# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto

# if we omit nav, mkdocs will automatically create a navigation section for us
# which will be alphanumerically sorted. I guess we'd want our own nav
# organization. But do we want to maintain our own nav structure?
# nav:
#   - Introduction: index.md
#   - "Disclaimers and Disclosures": disclaimers-and-disclosures.md

# we can prebuild the search index for better search performance at the cost of
# more bandwidth consumption
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      prebuild_index: true

extra_css:
  - css/image_toggle.css
  - css/youtube_toggle.css
  - css/lite-yt-embed.css
extra_javascript:
  - js/lite-yt-embed.js

theme:
  name: material
  # add folder with name overrides to override theme
  # custom_dir: overrides/
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - header.autohide
    - navigation.indexes
  # use google fonts — not sure if we're okay with this. Should we simply
  # fallback to system fonts? A consistent font experience sounds nice though.
  font:
    text: Inter
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light Mode

# we can use these extensions
# https://python-markdown.github.io/extensions/
# https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
markdown_extensions:
  - sane_lists
  - toc:
      permalink: "#"
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.magiclink
  - footnotes
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/IndiaInvestments/
      name: IndiaInvestments on Reddit
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hqBNg4u
      name: IndiaInvestments on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/indiainvestments
      name: IndiaInvestments on GitHub
    - icon: fontawesome/regular/envelope
      link: mailto:hello@indiainvestments.wiki
      name: Send a Mail to IndiaInvestments

copyright: >-
  &copy; Licensed Under
  <a href=https://creativecommons.org/licenses/by-nc/4.0/>
  CC BY-NC 4.0</a>

nav:
  - FAQs:
      - Mutual Funds and ETFs:
          - What is the best mutual fund app for investments?: faqs/mfs/best-mutual-fund-app-for-investments.md
          - Why should I invest in Direct Plans instead of Regular Plans?: faqs/mfs/direct-vs-regular.md
          - What's the best mutual fund I can invest in?: faqs/mfs/whats-the-best-mutual-fund-i-can-invest-in.md
          - Which date(s) is/are best for SIP in a month?: faqs/mfs/which-date-s-is-are-best-for-sip-in-a-month.md
          - I've to invest in ELSS for 80C tax saving. Which fund(s) should I pick?: faqs/mfs/ive-to-invest-in-elss-for-80c-tax-saving.-which-fund-s-should-i-pick.md
          - Should I get a Demat Account to buy units in Mutual Funds?: faqs/mfs/should-i-get-a-demat-account-to-buy-units-in-mutual-funds.md
          - Lumpsum investment vs SIP/DCA: faqs/mfs/lumpsum-investment-vs-sip-dca.md
          - Why are Index Funds in India not as cheap as Vanguard's Index Funds and ETFs?: faqs/mfs/why-are-index-funds-in-india-not-as-cheap-as-vanguards-index-funds-and-etfs.md
      - Insurance:
          - Should I invest in this LIC policy?: faqs/insurance/should-i-invest-in-this-lic-policy.md
          - Opinions on investing in smart wealth plan by bank?: faqs/insurance/opinions-on-investing-in-smart-wealth-plan-by-bank.md
          - Up to what age should I take term cover?: faqs/insurance/up-to-what-age-should-i-take-term-cover.md
          - Do I need my own health insurance? Employer already has group policy: faqs/insurance/do-i-need-my-own-health-insurance-employer-already-has-group-policy.md
          - Should I take top-up policy or super top-up?: faqs/insurance/top-up-vs-super-top-up.md
          - Is it worth paying extra premium for term insurance?: faqs/insurance/extra-premium-term-cover.md
      - Stocks:
          - Should I invest in smallcase?: faqs/stocks/is-smallcase-a-good-investment-returns-look-good.md
          - What is the best app for buying or trading stocks?: faqs/stocks/what-is-the-best-app-for-buying-or-trading-stocks.md
          - Which screener(s) should I use?: faqs/stocks/which-screener.md
          - The Stock Market Has Crashed. Which Stocks Should I Buy?: faqs/stocks/stock-market-crash-which-stocks-should-i-buy.md
      - Foreign Investing:
          - Why should I invest in the US markets?: faqs/foreign-invest/why-should-i-invest-in-the-us-markets.md
          - How should I invest in US equity?: faqs/foreign-invest/how-should-i-invest-in-us-equity.md
      - Tax:
          - I don't have any tax to pay. Do I still have to file ITR?: faqs/tax/i-dont-have-any-tax-to-pay.-do-i-still-have-to-file-itr.md
      - Miscellaneous:
          - Where can I park money for a few days, a few months, or a few years?: faqs/misc/where-can-i-park-money-for-a-few-days-a-few-months-or-a-few-years.md
          - What are chit funds? Should I invest?: faqs/misc/explain-like-i-am-5-eli5-chit-funds.md
          - Is Gold a good investment now? It has gone up ~50% this year: faqs/misc/is-gold-a-good-investment-now-it-has-gone-up-50-this-year.md
  - How To:
      - How to transfer shares from one demat account to another: how-to/how-to-transfer-shares-from-one-demat-account-to-another.md
      - How to move from one mutual fund platform to another: how-to/how-to-move-from-one-mutual-fund-platform-to-another.md
      - How to switch a Mutual Fund from Regular to Direct Plan: how-to/how-to-switch-the-mutual-fund-from-regular-to-direct-plan.md
      - How to file SEBI SCORES complaint?: how-to/how-to-file-sebi-scores-complaint.md
      - How to Update Nominee Details?: how-to/update-nominee-details.md
      - How to rematerialize mutual fund from demat form: how-to/rematerialize-demat-mf.md
      - How to Pay Advance Tax: how-to/how-to-pay-advance-tax.md
  - Stocks:
      - stocks/index.md
      - Can You Beat the Market?: stocks/can-you-beat-the-market.md
      - Reading an Annual Report: stocks/reading-an-annual-report.md
      - Researching a Sector: stocks/researching-a-sector.md
      - Financial Metrics and Ratios:
          - stocks/financial-metrics-and-ratios/README.md
          - Profitability: stocks/financial-metrics-and-ratios/profitability.md
      - Using Screeners: stocks/using-screeners.md
      - Due-Diligence Checklist: stocks/due-diligence-checklist.md
      - Work in Progress:
          - stocks/under-progress/README.md
          - Diving Deeper into Businesses: stocks/under-progress/understanding-the-business-of-a-company.md
          - Efficiency: stocks/under-progress/efficiency.md
          - Liquidity and Solvency: stocks/under-progress/liquidity-and-solvency.md
  - Excel:
      - Excel for Fun and Profit: excel/index.md
      - Reactive UI & Updates: excel/reactivity.md
      - Using External Data:
          - Google Finance: excel/using-external-data-google-finance.md
          - Working with CSV Format: excel/using-external-data-working-with-csv-format/README.md
          - CSV Format: excel/using-external-data-working-with-csv-format/csv-format.md
          - Computing LTCG Eligible Equity Units: excel/using-external-data-working-with-csv-format/computing-ltcg-eligible-equity-units.md
          - Process for Estimating Tax: excel/using-external-data-working-with-csv-format/process-for-estimating-tax.md
      - Quantifying Returns:
          - CAGR and XIRR: excel/quantifying-returns-cagr-and-xirr/README.md
          - CAGR - Point-to-Point Annualized Returns: excel/quantifying-returns-cagr-and-xirr/cagr.md
          - A Gentle Introduction to XIRR: excel/quantifying-returns-cagr-and-xirr/xirr.md
          - A Rigorous Introduction to XIRR: excel/quantifying-returns-cagr-and-xirr/xirr-math.md
  - Bonds:
      - Bond Basics: bonds/index.md
      - Government Securities: bonds/section-2-government-securities.md
      - Corporate Bonds: bonds/corporate-bonds.md
  - Miscellaneous:
      - Miscellaneous: misc/miscellaneous.md
      - US Investing: misc/us-investing.md
      - Recommended Reading: misc/recommended-reading.md
  - New to Investing:
      - Zero to Investing:
          - start-here/zero-to-investing/README.md
          - Getting Started: start-here/zero-to-investing/getting-started.md
          - Part Two - Defensive Setup: start-here/zero-to-investing/part-two-defensive-setup.md
          - Part Three - Spending Pattern: start-here/zero-to-investing/part-three-spending-pattern.md
          - Part Four - How to Invest: start-here/zero-to-investing/part-four-how-to-invest.md
      - Investment Philosophy and Strategy:
          - start-here/investment-philosophy-and-strategy/README.md
          - Basics of Investment Strategy Plan: start-here/investment-philosophy-and-strategy/basics-of-investment-strategy-plan.md
          - A simple Financial Planning Roadmap: start-here/investment-philosophy-and-strategy/a-simple-financial-planning-roadmap.md
          - Various types of Risks in Investments: start-here/investment-philosophy-and-strategy/various-types-of-risks-in-investments.md
          - Are you a Stock or Bond?: start-here/investment-philosophy-and-strategy/are-you-a-stock-or-bond.md
          - Assets and Asset Allocation: start-here/investment-philosophy-and-strategy/assets-and-asset-allocation.md
          - Critical Mass: start-here/investment-philosophy-and-strategy/critical-mass.md
          - Asset Rebalancing: start-here/investment-philosophy-and-strategy/asset-rebalancing.md
          - Lumpsum or SIP/STP: start-here/investment-philosophy-and-strategy/lumpsum-or-sip-stp.md
      - Insurance:
          - start-here/insurance-policies/README.md
          - Life:
              - start-here/insurance-policies/life/README.md
              - Life Insurance - What it is exactly?: start-here/insurance-policies/life/term-insurance.md
              - How to Evaluate Life Insurance Needs: start-here/insurance-policies/life/how-to-evaluate-life-insurance-needs.md
              - ULIP - Unit Linked Insurance Plan: start-here/insurance-policies/life/ulip.md
              - Some FAQs on Life Insurance: start-here/insurance-policies/life/faqs.md
              - Links to Answers related to Life Insurance: start-here/insurance-policies/life/links.md
          - Health: start-here/insurance-policies/health.md
          - Others - Disability & Home: start-here/insurance-policies/others-disability-home.md
          - Child Plan: start-here/insurance-policies/child-plan.md
      - All About Mutual Funds:
          - start-here/all-about-mutual-funds/README.md
          - What is a Mutual Fund?: start-here/all-about-mutual-funds/what-is-mutual-fund.md
          - Types of Mutual Funds: start-here/all-about-mutual-funds/types-of-mutual-funds.md
          - What and Why of Mutual Fund Ratings: start-here/all-about-mutual-funds/what-and-why-mutual-fund-ratings.md
          - How to Select a Mutual Fund: start-here/all-about-mutual-funds/how-to-select-mutual-fund.md
          - FAQs for Mutual Funds: start-here/all-about-mutual-funds/faqs.md
          - SIP and Mandates: start-here/all-about-mutual-funds/sip-and-mandates.md
          - How to Become Crorepati using Mutual Funds: start-here/all-about-mutual-funds/how-to-become-crorepati-using-mfs.md
          - Analysis using long term equity and debt funds in India: start-here/all-about-mutual-funds/analysis-long-term-equity-and-debt-funds-india.md
      - Retirement:
          - start-here/retirement/README.md
          - Primer on Retirement Planning: start-here/retirement/retirement-planning.md
          - Why You should not Opt for a Readymade Pension Plan: start-here/retirement/readymade-pension-plan.md
          - Studies of Long Term Portfolios and Retirement Withdrawal Rate Suggestions: start-here/retirement/long-term-portfolios-and-withdrawal-rate.md
          - Do-It-Yourself Retirement Plan: start-here/retirement/diy-retirement.md
      - Personal Finance: start-here/personal-finance.md
      - Behavioral Biases: start-here/behavioral-biases.md
      - ELI5 Series:
          - start-here/eli5-series/README.md
          - Time Value of Money: start-here/eli5-series/time-value-of-money.md
          - Inflation: start-here/eli5-series/inflation.md
          - Life Insurance: start-here/eli5-series/life-insurance.md
          - ELI5 guide to Selecting an Equity Mutual Fund: start-here/eli5-series/eli5-guide-to-selecting-an-equity-mutual-fund.md
          - How do I start investing in mutual funds [ELI5 series]: start-here/eli5-series/how-do-i-start-investing-in-mutual-funds-eli5-series.md
          - Mis-selling of Insurance Products: start-here/eli5-series/mis-selling-of-insurance-products.md
  - Contributors:
      - How Can I Start Contributing?: contributors/index.md
      - What is a Contributor License Agreement and why are we using it?: contributors/what-is-a-contributor-license-agreement-and-why-are-we-using-it/README.md
      - Contributor License Agreement: contributors/what-is-a-contributor-license-agreement-and-why-are-we-using-it/contributor-license-agreement.md
      - How to link FAQ via bot in Discord: contributors/how-to-link-faq-via-bot-in-discord.md
      - Style Guides: contributors/style-guides/README.md
      - General Style Guide: contributors/style-guides/general-style-guide.md
      - FAQ Style Guide: contributors/style-guides/faq-style-guide-1.md
      - How To Style Guide: contributors/style-guides/how-to-style-guide.md
      - Excel Series Style Guide: contributors/style-guides/excel-series-style-guide.md
      - Stocks Style Guide: contributors/style-guides/stocks-style-guide.md
  - Discord and Reddit:
      - How to Search the Wiki From Discord: discord-and-reddit/search-wiki-discord.md
      - I'm unable to send messages to stocks-fundamentals channel on Discord. Why?: discord-and-reddit/im-unable-to-send-messages-to-stocks-fundamentals-channel-on-discord-why.md
