---
name: publish mkdocs wiki

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: upgrade pip, install mkdocs material, and some extensions
        run: >-
          python -m pip install --upgrade pip mkdocs-material
          mkdocs-git-revision-date-localized-plugin
      - name: deploy pandoc to convert gitbook markdown to mkdocs markdown
        uses: docker://pandoc/core:2.14.0.1
        with:
          entrypoint: /bin/sh
          args: -c "find docs/ -name '*.md' -type f -exec pandoc --wrap=preserve -s -f markdown -t markdown_strict+yaml_metadata_block+pipe_tables+tex_math_dollars {} -o {}  \;"
      - name: add the changes to git, commit them, and push
        run: >-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -u
          git commit -m "markdown sanitized"
          git push origin master
      - name: deploy mkdocs in gh-pages
        run: mkdocs gh-deploy --force
